#!/usr/bin/env tsx
/**
 * Reads all IDEA.md files from the ideas directory and outputs
 * rvahacks/src/data/idea-content.ts as a Record<slug, markdown>.
 *
 * Usage: npx tsx generate-idea-content-data.ts
 */

import { readdirSync, readFileSync, writeFileSync, statSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const HACKATHON_ROOT = join(__dirname, "..");
const IDEAS_ROOT = join(HACKATHON_ROOT, "ideas");
const OUT_FILE = join(HACKATHON_ROOT, "..", "rvahacks", "src", "data", "idea-content.ts");

function findIdeaFiles(): Array<{ slug: string; path: string }> {
  const results: Array<{ slug: string; path: string }> = [];

  for (const pillarDir of readdirSync(IDEAS_ROOT)) {
    if (pillarDir.startsWith("_") || pillarDir.endsWith(".md") || pillarDir.endsWith(".json") || pillarDir.endsWith(".txt")) continue;
    const pillarPath = join(IDEAS_ROOT, pillarDir);
    if (!statSync(pillarPath).isDirectory()) continue;

    for (const ideaDir of readdirSync(pillarPath)) {
      if (ideaDir.startsWith("_")) continue;
      const ideaFile = join(pillarPath, ideaDir, "IDEA.md");
      try {
        statSync(ideaFile);
        results.push({ slug: ideaDir, path: ideaFile });
      } catch {
        // no IDEA.md
      }
    }
  }

  return results.sort((a, b) => a.slug.localeCompare(b.slug));
}

function escapeTemplateLiteral(str: string): string {
  return str.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

const files = findIdeaFiles();
console.log(`Found ${files.length} IDEA.md files`);

const entries = files.map(({ slug, path }) => {
  const content = readFileSync(path, "utf-8").trimEnd();
  console.log(`  ${slug}: ${content.split("\n").length} lines`);
  return `  "${slug}": \`${escapeTemplateLiteral(content)}\``;
});

const output = `// Auto-generated by scripts/generate-idea-content-data.ts
// Do not edit manually — re-run the script to regenerate.
// ${files.length} ideas with IDEA.md content.
export const ideaContentBySlug: Record<string, string> = {
${entries.join(",\n\n")}
};
`;

writeFileSync(OUT_FILE, output, "utf-8");
console.log(`\nWrote ${OUT_FILE}`);
console.log(`File size: ${(output.length / 1024).toFixed(1)} KB`);
