#!/usr/bin/env tsx
/**
 * Reads all UNIVERSE_EXPANSION.md files from the ideas directory,
 * strips the auto-generated header (first 6 lines), and outputs
 * rvahacks/src/data/universe-expansion.ts as a Record<slug, markdown>.
 *
 * Usage: npx tsx generate-universe-expansion-data.ts
 */

import { readdirSync, readFileSync, writeFileSync, statSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const HACKATHON_ROOT = join(__dirname, "..");
const IDEAS_ROOT = join(HACKATHON_ROOT, "ideas");
const OUT_FILE = join(HACKATHON_ROOT, "..", "rvahacks", "src", "data", "universe-expansion.ts");

function stripGeneratedHeader(content: string): string {
  // Strip the 6-line header:
  //   # Universe Expansion — <name>
  //   (blank)
  //   _Research generated by Parallel.ai..._
  //   (blank)
  //   ---
  //   (blank)
  const lines = content.split("\n");
  // Find the first `---` line and skip it plus the following blank line
  const hrIndex = lines.findIndex((l) => l.trim() === "---");
  if (hrIndex === -1) return content;
  // Skip everything up to and including the blank line after `---`
  const start = hrIndex + 1;
  // Skip a trailing blank line after the HR
  const actualStart = lines[start]?.trim() === "" ? start + 1 : start;
  return lines.slice(actualStart).join("\n").trimEnd();
}

function findUniverseExpansionFiles(): Array<{ slug: string; path: string }> {
  const results: Array<{ slug: string; path: string }> = [];

  for (const pillarDir of readdirSync(IDEAS_ROOT)) {
    if (pillarDir.startsWith("_") || pillarDir.endsWith(".md") || pillarDir.endsWith(".json") || pillarDir.endsWith(".txt")) continue;
    const pillarPath = join(IDEAS_ROOT, pillarDir);
    if (!statSync(pillarPath).isDirectory()) continue;

    for (const ideaDir of readdirSync(pillarPath)) {
      if (ideaDir.startsWith("_")) continue;
      const ueFile = join(pillarPath, ideaDir, "UNIVERSE_EXPANSION.md");
      try {
        statSync(ueFile);
        results.push({ slug: ideaDir, path: ueFile });
      } catch {
        // file doesn't exist
      }
    }
  }

  return results.sort((a, b) => a.slug.localeCompare(b.slug));
}

function escapeTemplateLiteral(str: string): string {
  // Escape backticks and ${} in template literal strings
  return str.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

const files = findUniverseExpansionFiles();
console.log(`Found ${files.length} UNIVERSE_EXPANSION.md files`);

const entries = files.map(({ slug, path }) => {
  const raw = readFileSync(path, "utf-8");
  const content = stripGeneratedHeader(raw);
  console.log(`  ${slug}: ${content.split("\n").length} lines`);
  return `  "${slug}": \`${escapeTemplateLiteral(content)}\``;
});

const output = `// Auto-generated by scripts/generate-universe-expansion-data.ts
// Do not edit manually — re-run the script to regenerate.
// ${files.length} ideas with Universe Expansion research.
export const universeExpansionBySlug: Record<string, string> = {
${entries.join(",\n\n")}
};
`;

writeFileSync(OUT_FILE, output, "utf-8");
console.log(`\nWrote ${OUT_FILE}`);
console.log(`File size: ${(output.length / 1024).toFixed(1)} KB`);
